name: "Unit tests: macOS"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:

  build-and-test:
    name: Unit tests on macOS
    runs-on: ${{ matrix.os }}
    if:  ${{ github.event_name == 'pull_request' || github.repository == 'PalamaraLab/ASMC' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
          - os: macos-14

    steps:

      - name: checkout repo & submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: cache vcpkg installed packages
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            vcpkg/
            build_dir/vcpkg_installed/
          key: ${{ runner.os }}-${{ hashFiles('vcpkg.json', 'vcpkg/CHANGELOG.md') }}

      - name: install dependencies
        run: |
          brew install libomp llvm@17 pkg-config

      - name: make build directory
        run: mkdir -p build_dir

      - name: cmake configure
        run: cmake .. -DCMAKE_CXX_COMPILER=$(brew --prefix llvm@17)/bin/clang++ -DCMAKE_C_COMPILER=$(brew --prefix llvm@17)/bin/clang
        working-directory: build_dir

      - name: cmake build
        run: cmake --build . --parallel 3 --target ASMC_unit_tests
        working-directory: build_dir

      - name: cmake test
        run: ctest -j2 -R Asmc_unit_tests --output-on-failure
        working-directory: build_dir
