name: Regression test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:

  build-and-test:
    name: Regression test on Ubuntu
    runs-on: ubuntu-22.04
    env:
      CXX: g++-10
    if: ${{ github.event_name == 'pull_request' || github.repository == 'PalamaraLab/ASMC' }}

    steps:
      - name: checkout repo & submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: cache vcpkg installed packages
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            vcpkg/
            build_dir/vcpkg_installed/
          key: ${{ runner.os }}-${{ env.CXX }}-${{ hashFiles('vcpkg.json', 'vcpkg/CHANGELOG.md') }}

      - name: make build directory
        run: mkdir -p build_dir

      - name: cmake configure
        run: cmake .. -DCMAKE_BUILD_TYPE=Release
        working-directory: build_dir

      - name: cmake build
        run: cmake --build . --parallel 2 --target ASMC_regression
        working-directory: build_dir

      - name: cmake test
        run: ctest -R regression --output-on-failure
        working-directory: build_dir
