name: Ubuntu no sse/avx

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:

  build-and-test:
    name: Unit tests with out sse/avx on Ubuntu
    runs-on: ubuntu-24.04
    if: ${{ github.event_name == 'pull_request' || github.repository == 'PalamaraLab/ASMC' }}

    steps:

      - name: checkout repo & vcpkg submodule
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: make build directory
        run: mkdir -p build_dir

      - name: cmake configure
        run: cmake .. -DASMC_FORCE_PURE:BOOL=TRUE
        working-directory: build_dir

      - name: cmake build
        run: cmake --build . --parallel 2 --target ASMC_unit_tests
        working-directory: build_dir

      - name: cmake test
        run: ctest -j2 -R Asmc_unit_tests --output-on-failure
        working-directory: build_dir
