name: Regression test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: Regression test on Ubuntu latest
    runs-on: ubuntu-20.04
    env:
      CXX: g++-10
    if: ${{ github.event_name == 'pull_request' || github.repository == 'PalamaraLab/FastSMC' }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: cache vcpkg installed packages
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            vcpkg/
            build_dir/vcpkg_installed/
          key: ${{ runner.os }}-${{ env.CXX }}-${{ hashFiles('vcpkg.json', 'vcpkg/CHANGELOG.md') }}

      - name: make build directory
        run: mkdir build_dir
        if: steps.cache.outputs.cache-hit != 'true'

      - name: cmake configure
        run: cmake .. -DCMAKE_BUILD_TYPE=Release
        working-directory: build_dir

      - name: cmake build
        run: cmake --build . --parallel 2 --target ASMC_regression
        working-directory: build_dir

      - name: cmake test
        run: ctest -R regression --output-on-failure
        working-directory: build_dir
