name: Regression test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:

  build-and-test:
    name: Regression test on Ubuntu
    runs-on: ubuntu-24.04
    env:
      CXX: g++-10
    if: ${{ github.event_name == 'pull_request' || github.repository == 'PalamaraLab/ASMC' }}

    steps:
      - name: checkout repo & submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: install deps
        run: |
          sudo apt -y update
          sudo apt -y install libboost-iostreams-dev libboost-program-options-dev zlib1g-dev

      - name: make build directory
        run: mkdir -p build_dir

      - name: cmake configure
        run: cmake .. -DCMAKE_BUILD_TYPE=Release
        working-directory: build_dir

      - name: cmake build
        run: cmake --build . --parallel 2 --target ASMC_regression
        working-directory: build_dir

      - name: cmake test
        run: ctest -R regression --output-on-failure
        working-directory: build_dir
